analyzer:
  exclude:
    - "**/*.g.dart"  # Exclude generated files
  issues:
    - avoid_print
    - avoid_web_libraries_in_flutter
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - unnecessary_new
    - unnecessary_string_interpolations
    - use_build_context_synchronously
    - prefer_const_declarations
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - unnecessary_null_comparison
    - prefer_if_null
    - use_function_type_syntax
    - prefer_expression_function_bodies
    - avoid_types_as_parameter_types
    - avoid_dynamic_calls_in_directives
    - avoid_dynamic_method_lookup
    - avoid_dynamic_property_lookup
    - avoid_setters_without_getters
    - avoid_types_in_extended_list_literals
    - avoid_types_in_extended_map_literals
    - use_string_interpolation
    - prefer_equal_equal
    - prefer_is_not_null
    - prefer_is_null
    - prefer_void_to_null
    - prefer_final_locals
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - prefer_expression_function_bodies
    - prefer_if_null
    - use_function_type_syntax
    - avoid_types_as_parameter_types
    - avoid_dynamic_calls_in_directives
    - avoid_dynamic_method_lookup
    - avoid_dynamic_property_lookup
    - avoid_setters_without_getters
    - avoid_types_in_extended_list_literals
    - avoid_types_in_extended_map_literals
    - use_string_interpolation
    - prefer_equal_equal
    - prefer_is_not_null
    - prefer_is_null
    - prefer_void_to_null
    - prefer_final_locals
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - prefer_expression_function_bodies
    - prefer_if_null
    - use_function_type_syntax
    - avoid_types_as_parameter_types
    - avoid_dynamic_calls_in_directives
    - avoid_dynamic_method_lookup
    - avoid_dynamic_property_lookup
    - avoid_setters_without_getters
    - avoid_types_in_extended_list_literals
    - avoid_types_in_extended_map_literals
    - use_string_interpolation
    - prefer_equal_equal
    - prefer_is_not_null
    - prefer_is_null
    - prefer_void_to_null
    - prefer_final_locals
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - prefer_expression_function_bodies
    - prefer_if_null
    - use_function_type_syntax
    - avoid_types_as_parameter_types
    - avoid_dynamic_calls_in_directives
    - avoid_dynamic_method_lookup
    - avoid_dynamic_property_lookup
    - avoid_setters_without_getters
    - avoid_types_in_extended_list_literals
    - avoid_types_in_extended_map_literals
    - use_string_interpolation
    - prefer_equal_equal
    - prefer_is_not_null
    - prefer_is_null
    - prefer_void_to_null
    - prefer_final_locals
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - prefer_expression_function_bodies
    - prefer_if_null
    - use_function_type_syntax
    - avoid_types_as_parameter_types
    - avoid_dynamic_calls_in_directives
    - avoid_dynamic_method_lookup
    - avoid_dynamic_property_lookup
    - avoid_setters_without_getters
    - avoid_types_in_extended_list_literals
    - avoid_types_in_extended_map
